### PR TITLE
Added Serbian translation

### PR DESCRIPTION
**Pull request by kostich**

### CODE REVIEW

**Comment by mrdokenny** [comment]
I'm going to change it manually. Thanks anyway.

**Comment by kostich** [comment]
Ah, so you would like for 'Cookie AutoDelete' to be left as is? Like what's done with the trademarks?

**Comment by mrdokenny** [comment]
@kostich Yes 😉

**Comment by kostich** [comment]
Ok, will take that in account the next time I update the translations. :)

**Pull request merged**
