### PR TITLE
Add regexp support for white-list rules

### PR DESCRIPTION
**Pull request by maltsev**
In #646 we discussed how C-AD could be used as an anti-distraction extension. I decided to choose the easiest path and just add regexp support to white-list rules. In the UI it looks the following way: 
image

By default, it's unchecked so users who don't know what regexps are could just simply ignore that.

I've tested this change and it works well both in FF and Chrome.

I was not sure if it's a good place in the UI to put that option. Maybe you could suggest a better place?

I could also update the wiki if this PR gets merged.

_(this PR also relates to #169)_

### CODE REVIEW

**Comment by kennethtran93** [comment]
Thanks!

Would it be more feasible if it could just check if the expression entered is a regex? (i.e. check for `/` as the first character and `/` as the end character? That would eliminate the RegExp checkbox.

**Comment by kennethtran93** [comment]
Heads up #650 is my PR with a bunch of changes.  As it is late night for me I won't merge my PR yet just in case I missed something in the morning.

**Comment by maltsev** [comment]
Thanks for letting me know! Can you wait a bit with releasing a new version of C-AD? I'll implement the regexp the way you suggested in ≈10 hours.

**Comment by maltsev** [comment]
I've added check for `/` as a first and a last char.

**Comment by kennethtran93** [comment]
While the regexp works in what you have given me, I'm also fixing a bug that surfaced due to using regexp as the 'keep all cookies' unchecked would show nothing.  This is because the cookies.getAll was expecting an actual domain and not a regexp.  I'm going to add an additional check and filter to the 'keep all cookies' unchecked so it would only show cookies if the domain matches the regexp given.

**Review by kennethtran93 — APPROVED** [review]
Thanks for the addition of testing with the enhancement.

**Comment by kennethtran93** [comment]
Will Close #169 with this

**Comment by kennethtran93** [comment]
Thanks!

**Pull request merged**
