### PR TITLE
Added Option for Right-Click ContextMenus.

### LINKED ISSUE #766: [FEATURE REQUEST]  Make the new context menus optional, if it's easy.
**Is your feature request related to a problem? Please describe.**

Hello. You asked - over a week ago, admittedly - to take a look at the dev build including the new grand feature set that was merged as #753 .
It solved my issue regarding per-container cleanup, as far as I can see, thanks once agian.

But it also includes multiple other brand new features, the biggest of which is a CAD's own right click submenu to offer access to CAD features in popup windows lacking the toolbar.

This is a very valid need, but I personally don't need it (I identify the domains to gray/white via the cleanup log after an action such as popup-driven log-in fails) and the additional menu entry just gets in the way - it's a largeish multi-level submenu with a bright icon calling out for attention in a black-themed menu.
I generally do all I can to cut the right click menu to minimum, disable it for all other extensions (like uBO) and hide some Firefox's standard entries with userChrome.css.

**Describe the solution you'd like**

if it's as easy as one more settings panel checkbox and a a condition check in the place where the menu's registered with FIrefox today, I would very much appreciate if you'd make the menu toggleable (most probably on by default?).

**Describe alternatives you've considered**

It's very much a "if it's super easy and if you have time" kind of request.

If it's more complex, or would cause problems, I'll try to find a way to hide it with userChrome.css (hopefully the menu elements ID is tied to some static or semi-static extension ID) or worst case just clench teeth and live with it.

**Additional context**

I apologize for stirring a fuss about such an objectively small problem.
Best regards...

### PR DESCRIPTION
**Pull request by kennethtran93**
Closes #766.  Per documentation in MDN, seems contextMenus/menus cannot be put into `optionalpermissions` at this time...taking it as face value as there's not really a permission message for users at this time anyway.
Signed-off-by: Kenneth Tran <kennethtran93@users.noreply.github.com>

### CODE REVIEW

**Comment by kennethtran93** [comment]
...I'll work on Unit Test Coverage for this class I guess if you would like to include it through this PR.

Summary of Changes:
- Made right-click menu an option in settings
- made away with some warnings that showed up in WebStorm, including some that says that the `returning Promise was ignored` or something to that effect.

**Comment by kennethtran93** [comment]
Dev Build per e5bbf25:

[Cookie-AutoDelete_Dev_20200614_011159_Chrome.zip](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/4775722/Cookie-AutoDelete_Dev_20200614_011159_Chrome.zip)

[Cookie-AutoDelete_Dev_20200614_011159_Firefox.zip](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/files/4775724/Cookie-AutoDelete_Dev_20200614_011159_Firefox.zip)

**Comment by ke-d** [comment]
> ...I'll work on Unit Test Coverage for this class I guess if you would like to include it through this PR.

I'm going to try to separate the dependencies out in the untested classes to see how well it works when testing, so no need to put more effort into it for now.

**Comment by kennethtran93** [comment]
> I'm going to try to separate the dependencies out in the untested classes to see how well it works when testing, so no need to put more effort into it for now.

I had just completed it lol.  Let me know how that works out as well.

**Comment by kennethtran93** [comment]
After this PR, all that should be left is the localization updates in #760 that this will also sync with Crowdin for updates before I release the next version 3.4.0.

**Review by ke-d — APPROVED** [review]

**Pull request merged**
