### PR TITLE
Fix popup reflow.

### PR DESCRIPTION
**Pull request by seansfkelley**
Addresses #178 and some of #174.

This PR updates Bootstrap to version 4 to get flexbox-based grids, which are considerably easier to use and tweak.

The visuals now have slightly different sizes/colors per the Bootstrap update (I kind of like it, the buttons were pretty huge before).

image

When Cookie AutoDelete is stuck into the "more" menu, it now shrinks to fit. It isn't the most amazing visuals in the world, but this was an issue before the UI redesign and I want to get the fix out there sooner rather than later. These changes _should_ also make it more tolerant of being on a mobile device, though as noted on my previous PRs, I don't have a phone to test this on and can only check by noodling my desktop browser's size.

(FF 56 on OS X)

image

I also had to make some slight changes to the buttons on the Expressions settings page to bring them up to speed. I verified there are no behavioral regressions in them w/r/t the commit this PR is forked from.

### CODE REVIEW

**Comment by ghost** [comment]
Are you aware of this?
image
Text in "Clean, include open tabs" button may be very long in other languages https://crowdin.com/translate/cookie-autodelete/31/en-pl#930

**Comment by seansfkelley** [comment]
Yeah, it's pretty long already in English. I'm tooling around with a design that's more halfway between this one and the previous design to accommodate lengthy lines/phones better, but I wanted to get this change out there quickly so it at least wasn't totally busted for some users.

**Comment by ke-d** [comment]
I think the upgrade to Bootstrap 4.0 caused this issue with this nav tab for Containers Tab Mode.

Original:
capture1

This PR:
capture2

**Comment by seansfkelley** [comment]
@mrdokenny fixed contextual identities. Are there other bits of UI that don't appear with the default configuration I should check?

**Comment by ke-d** [comment]
@seansfkelley Seems like in #182 and #183 the problem might be the UI is too wide. So maybe combining the two clean functions into one and just using a dropdown like what you proposed here:

image

image

**Comment by ke-d** [comment]
I'll merge this as is for now while I fix a couple of issues.

**Pull request merged**
