### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zero77**
Related to:
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/discussions/949

### CODE REVIEW

**Comment by zero77** [comment]
Have i missed anything.

**Comment by kennethtran93** [comment]
Great start.  Perhaps add in a column for Firefox users i.e. `Per Container (contextual identities)` and could put yes to relevant ones with an asterisk `*` to link to a note regarding cross-container issues for non-cookie items?

**Comment by zero77** [comment]
> Great start. Perhaps add in a column for Firefox users i.e. Per Container (contextual identities).

Would contextual identities, be ok as a column header.

> Could put yes to relevant ones with an asterisk * to link to a note regarding cross-container issues for non-cookie items?

I was expecting that any related issues would be added to Known Issues.

Also, does this mean some of the Cleanable Data types are not out of scope and being considered.
If so i will change "Out Of Project Scope" to something like under revue.

**Comment by kennethtran93** [comment]
> Would contextual identities, be ok as a column header.

Probably Containers would be better as it is more of a user term, while `contextualIdentites` is more of a backend/coder term.

> 
> > Could put yes to relevant ones with an asterisk * to link to a note regarding cross-container issues for non-cookie items?
> 
> I was expecting that any related issues would be added to Known Issues.

Good point.  Yes do that then.  It is more of a browser limitation at this time than from CAD end.

> Also, does this mean some of the Cleanable Data types are not out of scope and being considered.
> If so i will change "Out Of Project Scope" to something like under revue.

I suppose.  You can put them all as **not implemented until cleanable by hostname** or something to that effect.

**Pull request closed without merging**
