### PR TITLE
translate UK (Ukrainian)

### PR DESCRIPTION
**Pull request by perdolka**

### CODE REVIEW

**Comment by ghost** [comment]
https://crowdin.com/project/cookie-autodelete

**Comment by perdolka** [comment]
@gwarser
I know about crowdin.
But the translation is already done.
Most of FF addons (on GH) don't use crowdin, so it's easier for me to translate "manually".

**Comment by kennethtran93** [comment]
@mrdokenny Should you just manually upload this to crowdin since this is currently in the 2.x branch?

**Comment by ke-d** [comment]
I just manually merged this into Crowdin. Thanks for the translation.

**Pull request closed without merging**
