### PR TITLE
Danish translation of 2.X.X

### PR DESCRIPTION
**Pull request by Johnny1000**
Danish translation of 2.X.X

### CODE REVIEW

**Comment by mrdokenny** [comment]
Just a heads up that there's probably going to be some more phrasing/wording changes in addition to the changes I made recently.

**Comment by Johnny1000** [comment]
Thanks for the heads up, mrdokenny :o)
I'll try to keep up as best I can :o)

**Comment by ke-d** [comment]
@Johnny1000 You typically don't need to update with all changes like in ba5b225. Usually you can just PR just the `da/messages.json`. I'm probably going to move to crowdin pretty soon.

**Comment by ke-d** [comment]
I added your 1.X.X locale on crowdin, so you just have to update it for 2.X.X

https://crowdin.com/project/cookie-autodelete

**Pull request closed without merging**
